## Kubernetes Job to run the simple-check batch container once
# Builds on the local image 'simple-check-app' (see simple-check/ directory)
# and executes a single Pod with no retries (backoffLimit=0, restartPolicy=Never).
# Update 'metadata.name' (or switch to 'generateName') for each new run to avoid name collisions.
# Apply with: kubectl apply -f k8s/job.yaml
apiVersion: batch/v1
kind: Job
metadata:
  # Use generateName so Kubernetes assigns a unique name (e.g. simple-check-job-abc123)
  generateName: simple-check-job-
spec:
  template:
    spec:
      containers:
      - name: check-container
        image: simple-check-app:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: TOTAL_TIMEOUT
          value: "30"
        - name: TARGET_URL
          value: "http://practice-service/health/ready"
      # A Job's pod should not be restarted if it fails.
      # We want to see the failure.
      restartPolicy: Never
  # If the job fails, don't automatically retry it.
  backoffLimit: 0
